services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  backend:
    build: ./backend
    ports:
      - "8000:8000"

  redis:
    image: redis
    hostname: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=SETPWDHERE
    ports:
      - 5432:5432
