services:
  redis:
    image: redis
    hostname: redis
    ports:
      - "6379:6379"
    # volumes:
    #   - ./redisstore:/data

  postgres:
    image: postgres:15
    hostname: postgres
    user: postgres
    environment:
      - POSTGRES_PASSWORD=SETPWDHERE
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    # volumes:
    #   - ./dbstore:/var/lib/postgresql/data
